### ISSUE TITLE
Is 0.1 working?

### ISSUE THREAD

**Issue by synapsiddigital** [Beaconstac/NearBee-iOS-SDK#1] opened 2019-03-12 19:00 UTC
Try as I might, I cannot get a new project following instructions step by step or the SampleApp to build.

**Comment by ravipratapm** [comment] 2019-03-12 19:30
Hi there - do you have an active Premium plan subscription to Beaconstac? It won't work without that.

**Comment by synapsiddigital** [comment] 2019-03-13 04:42
Hi Ravi, yes I've punched in the API token & Organisation ID as per the Readme but no luck, I seem to be having import errors, so wanted to confirm this version was functional. 

Also tried replacing these details in the Sample App but still, no luck...

**Comment by sachinmobstac** [comment] 2019-03-13 15:00
Hi @synapsiddigital,

Can you upload a screenshot of the issue issue are you facing with NearBee?

**Comment by synapsiddigital** [comment] 2019-03-13 16:31
Hi Sachin, thanks for your guys quick response I've managed to get a test build going using pieces from the sampleApp and a fresh Swift 4 project.

Is there any chance of emulating a Beaconstac beacon from a Laptop or phone? I've tried one emulator. Or will I need a physical Beaconstac Beacon? I can drive to my client but emulating would be nice!

**Comment by synapsiddigital** [comment] 2019-03-14 05:54
I managed to get the nearBee app downloaded from the App Store to sometimes pick up a signal I'm broadcasting but I'd say it works 1/10 times, however with the SDK implemented into my own Swift project I cannot pick-up anything, even though the console prints that nearBee is scanning for beacons.

**Comment by sachinmobstac** [comment] 2019-03-14 10:53
Hi @synapsiddigital,

Can you please install the NearBee app on your Android Phone and let me know the behavior? Also, the NearBee SDK can only be used with the Beaconstac beacons. Are you using the NearBee SDK with the Beaconstac beacons?

**Comment by synapsiddigital** [comment] 2019-03-14 10:55
hey @sachinmobstac will do on android and let you know. I've not yet tried with an actual beacon but I could get the official iOs app to pick-up one of my broadcasted beacons. I have arranged to get a physical one and will let you know how it goes 💪

**Comment by sachinmobstac** [comment] 2019-03-14 10:58
@synapsiddigital Sure, you have to use the Beaconstac beacons if you are going to use our SDK. It is designed to work only with the Beaconstac beacons.

**Comment by synapsiddigital** [comment] 2019-03-14 20:07
@sachinmobstac thanks, will let you know how it goes. But FYI as stated, the nearBee iOS app DOES pick-up a broadcasted BLE beacon from other manufacturers & a simulated one off a device (android), albeit intermittently. Chat soon.

**Comment by sachinmobstac** [comment] 2019-03-15 04:51
@synapsiddigital, The NearBee iOS app does pick-up all the beacons which broadcast Eddystone URL and Eddystone UID frames.

**Comment by synapsiddigital** [comment] 2019-03-15 04:53
@sachinmobstac is the SDK different in the sense it will only pick up a nearBee beacon?

**Comment by sachinmobstac** [comment] 2019-03-15 05:22
@synapsiddigital, Yes it picks up all the beacons which broadcast Eddystone URL and Eddystone UID. Since the SDK users will be interested with their own beacons, the SDK is restricted to work with their beacons only.

**Comment by synapsiddigital** [comment] 2019-03-19 20:08
Hi @sachinmobstac I can confirm SDK is pickup up broadcasts in app and rendering into the TableView.

Any tips on notifications? Can't see anything that handles them out the box.

**Comment by synapsiddigital** [comment] 2019-03-19 21:40
@sachinmobstac would you recommend this SDK or the React-Native version for iOS at this moment?

**Comment by sachinmobstac** [comment] 2019-03-20 05:58
@synapsiddigital, 
For notifications, please make sure you are the app is allowed to use Bluetooth in the background and the app has ALWAYS ALLOW location permission set. Also, it only works with the Beaconstac beacons and nothing else.

I am not sure about your requirement. What kind of app are you building, is it completely native (Objective-C or Swift) or it is based on react-native?

**Comment by synapsiddigital** [comment] 2019-03-20 06:38
@sachinmobstac the app simply needs to run on iOS and all it does is implement the nearBee scanner. I might build a nice UI on top of it but that's all we need. So wondering if you'd recommend this SDK or the React-Native. Will let you know how it goes regarding notifications.

**Comment by sachinmobstac** [comment] 2019-03-20 06:41
@synapsiddigital, Shall I close this and can you please contact me at support@beaconstac.com?

**Comment by synapsiddigital** [comment] 2019-03-20 06:47
If you prefer yes, I'll mail you there.

**Closed** 2019-03-20 07:09 UTC
